import {Dimensions, StyleSheet} from 'react-native';
const {width, height} = Dimensions.get('window');

export default StyleSheet.create({
  container: {
    flex: 1,
    // backgroundColor:'white'
  },
  viewItemIcon: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 3,
  },
  ViewHeader: {
    // backgroundColor: '#F27B13',
    height: 90,
    paddingHorizontal: 20,
  },

  TxtTextInput: {
    fontWeight: 'bold',
    fontSize: 14,
    width: width - 140,
    height: 50,
    lineHeight: 16,
  },

  ViewTitile: {
    flexDirection: 'row',
    alignItems: 'center',
    // marginTop: 5,
    width: '100%',
    marginTop: 20,
  },

  ViewPlus: {
    // position: 'absolute',
    // bottom: 30,
    // right: 20,
    marginTop: 15,
    width: 50,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ViewWrap: {
    width: width - 20,
    marginHorizontal: 10,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#FFF',
    // flexDirection: 'row',
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
  },
  ViewSearchContainer: {
    left: 0,
    right: 0,
    height: 90,
    marginTop: -90,
    flexDirection: 'row',
  },
  ViewSearch: {
    backgroundColor: '#FFF',
    paddingVertical: 8,
    paddingHorizontal: 20,
    marginHorizontal: 20,
    marginRight: 1,
    borderRadius: 15,
    marginTop: 15,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderColor: '#F27B13',
    borderWidth: 1,
  },
  TxtTitle: {
    fontSize: 14,
    // fontWeight: '800',
    color: 'gray',
    lineHeight: 24,
  },
  TxtDes: {
    fontSize: 14,
    color: 'black',
    lineHeight: 24,
    marginHorizontal: 6,
  },
  ViewCancel: {
    position: 'absolute',
    right: 10,
    top: 10,
    height: 30,
    width: 30,
    borderRadius: 20,
    backgroundColor: '#F27B13',
    justifyContent: 'center',
    alignItems: 'center',
  },

  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalView: {
    width: width - 80,
    height: 250,
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontSize: 16,
  },
  TouchSort: {
    height: 40,
    width: width - 80 - 60,
    alignSelf: 'center',
    borderBottomWidth: 0.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  ViewEdit: {
    position: 'absolute',
    right: 10,
    top: 100,
    height: 30,
    width: 30,
    // borderRadius: 20,
    // backgroundColor: 'red',
    justifyContent: 'center',
    alignItems: 'center',
  },
  infoInputView: {
    width: '110%',
    paddingHorizontal: 10,
    marginHorizontal: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderRadius: 8,
    borderWidth: 0.5,
    alignSelf: 'flex-start',
    height: 100,
  },
  touchSave: {
    backgroundColor: '#89c4e4',
    borderWidth: 0,
    width: '110%',
    marginVertical: 12,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
